Add kernel build and embed in hook OS (#183)
* first commit

* rename oci base

* rename

* add kernel make target

* add shebang

* try with hardcoded point release

* first try

* remove 6.x kernel code

* cleanup

* more cleanup

* Bump version

* resolve lint issues

* fix indent

* more cleanup

* remove patch application

* remove kernel build sh

* remove patch appy from Dockerfile

* build binaries using locally built kernel

* add make build-with-kernel target

* remove ENFORCE KERNEL VERSION

* cleanup build_hookos

* make common build target

* Add kernel push

* remove blank line

* check if yq is installed

* update README

* cleanup

* update README

* Align kernel dockerfile with Open source version

diff --git a/hook-os/Makefile b/hook-os/Makefile
--- a/hook-os/Makefile
+++ b/hook-os/Makefile
@@ -12,15 +12,15 @@ PROJECT_NAME := hook-os
 BINARY_NAME  := hook-os
 
 # Code versions, tags, and so on
-VERSION       := $(shell cat VERSION)
-VERSION_MAJOR := $(shell cut -c 1 VERSION)
-IMG_NAME      := provisioning-hook-os
-IMG_VERSION   ?= $(VERSION)
-GIT_COMMIT    ?= $(shell git rev-parse HEAD)
-BRANCH_NAME   ?= $(shell git rev-parse --abbrev-ref HEAD)
-OCI_REPOSITORY := edge-orch/en/files/${IMG_NAME}
-HOOK_KERNEL_REPOSITORY  := edge-orch/edge-node/hook-kernel
-HOOK_KERNEL_VERSION 	:= 5.10.228-e0637f99-dm-xz
+VERSION                     := $(shell cat VERSION)
+VERSION_MAJOR               := $(shell cut -c 1 VERSION)
+IMG_NAME                    := provisioning-hook-os
+IMG_VERSION                 ?= $(VERSION)
+GIT_COMMIT                  ?= $(shell git rev-parse HEAD)
+BRANCH_NAME                 ?= $(shell git rev-parse --abbrev-ref HEAD)
+OCI_REPOSITORY              := edge-orch/en/files/${IMG_NAME}
+HOOK_KERNEL_REPOSITORY      := edge-orch/edge-node/hook-kernel
+HOOK_KERNEL_POINT_RELEASE   :=228
 
 
 # Include shared makefile
@@ -38,11 +38,7 @@ $(COMPONENTS):
 	cd $@ && \
 	chmod +x build.sh && bash build.sh
 	
-pull-kernel:
-	docker pull ${RELEASE_SVC_URL}/${HOOK_KERNEL_REPOSITORY}:${HOOK_KERNEL_VERSION}
-	docker tag ${RELEASE_SVC_URL}/${HOOK_KERNEL_REPOSITORY}:${HOOK_KERNEL_VERSION} quay.io/tinkerbell/hook-kernel:5.10.228-e0637f99
-
-components: $(COMPONENTS) pull-kernel
+components: $(COMPONENTS)
 
 configure:
 	echo 'http_proxy=$(http_proxy)' > config
@@ -57,13 +53,35 @@ certs:
 	echo "" >> hook/files/idp/ca.pem
 	echo "" >> hook/files/idp/server_cert.pem
 
-build: configure certs components
-	@# Help: Runs build stage
+kernel:
+	cd hook/ && \
+	HOOK_KERNEL_OCI_BASE=${RELEASE_SVC_URL}/${HOOK_KERNEL_REPOSITORY} \
+	FORCE_BUILD_KERNEL="yes" \
+	KERNEL_POINT_RELEASE=${HOOK_KERNEL_POINT_RELEASE} \
+	bash ./build.sh kernel hook-default-amd64
+
+binaries:
+	@# Help: Runs build binaries stage
 	@echo "---MAKEFILE BUILD---"
-	@echo "--Updated step below--"
-	chmod +x build_hookos.sh && bash build_hookos.sh
+	chmod +x build_hookos.sh && \
+	HOOK_KERNEL_OCI_BASE=${RELEASE_SVC_URL}/${HOOK_KERNEL_REPOSITORY} \
+	KERNEL_POINT_RELEASE=${HOOK_KERNEL_POINT_RELEASE} \
+	bash build_hookos.sh
 	git stash -- hook/linuxkit-templates/hook.template.yaml
 	@echo "---END MAKEFILE Build---"
+
+build: configure certs components
+	@# Help: Runs build stage
+	@# Builds HookOS binaries. If the kernel image is not available in Release Service or locally, it first builds the kernel image.
+	@bash -c '$(MAKE) binaries 2> >(tee binarybuilderr.log >&2) || { \
+		if grep -q "Error 7" binarybuilderr.log; then \
+			echo "Found Error 7 in binarybuilderr.log, running `make kernel`..."; \
+			$(MAKE) kernel && $(MAKE) binaries; \
+		else \
+			echo "Exit code is not 7"; \
+		fi; \
+		rm binarybuilderr.log; \
+	}'
 
 SH_FILES := $(shell git ls-files | grep '\.sh$$' | grep -v '^hook/')
 lint: license shellcheck mdlint
@@ -78,12 +96,24 @@ test:
 	echo $@
 	@echo "---END MAKEFILE TEST---"
 
-artifact-publish:
+publish-binaries-ci:
 	@echo "Publishing Hook OS binary to Production Release Service."
 	cd $(OUT_DIR) && \
 	aws ecr create-repository --region us-west-2 --repository-name $(OCI_REPOSITORY) || true && \
 	oras push $(OCI_PATH):$(IMG_VERSION) --artifact-type application/vnd.intel.hookos.file hook_x86_64.tar.gz
 	@echo "---END MAKEFILE TEST---"
+
+push-kernel-ci:
+	@# Help: Pushes kernel image to Release Service
+	@# Pushes the Hook OS kernel image to the Release Service only if the image tag isn't already present in the Release Service.
+	@echo "Publishing Hook OS kernel to Production Release Service."
+	@image_name=$(shell cat hook/hook.hook-default-amd64.yaml | yq .kernel.image) && \
+	tag_name=$(shell cat hook/hook.hook-default-amd64.yaml | yq .kernel.image | cut -d':' -f2) && \
+	echo "Kernel Tag:" $$tag_name && \
+	docker pull $$image_name || docker tag $$image_name ${OCI_REGISTRY}/${HOOK_KERNEL_REPOSITORY}:$$tag_name && \
+	docker push ${OCI_REGISTRY}/${HOOK_KERNEL_REPOSITORY}:$$tag_name
+
+artifact-publish: publish-binaries-ci push-kernel-ci
 
 coverage:
 	@# Help: Runs coverage stage
