Improving checks for Jira tickets in PR descriptions (#307)
* Added new regex capture for Jira IDs

* Fixing syntax

Fixing syntax again

* Adding to github output for step data sharing

* Adding verbose flag to curl

* Using more efficient API endpoint

* Removing verbosity

* Github output cant take new line chars

Fixing logic issues

* Just checking for id API endpoint

* More logging

* Better error message

* Trying with GET explicit

* Adding automatic comment and better checking for multiple IDs

* Correct api endpoint

* verbosity

* Using 'Token' instead of 'Bearer'

* Trying -s -k flags and verify=false

* Remove verify=false

* Properly injecting secret

* Trying a different method

* There is a name discrepency in inventory config, hmmm

* Safer secret referencing

* Better error checking on the Jira api call

* Label checking not working

diff --git a/mi-onboarding-manager/.github/workflows/check-pr-reqs.yml b/mi-onboarding-manager/.github/workflows/check-pr-reqs.yml
--- a/mi-onboarding-manager/.github/workflows/check-pr-reqs.yml
+++ b/mi-onboarding-manager/.github/workflows/check-pr-reqs.yml
@@ -5,22 +5,80 @@
 on:
   pull_request:
     types:
-    - opened
-    - synchronize
-    - reopened
-    - edited
+      - labeled
+      - opened
+      - synchronize
+      - reopened
+      - edited
 jobs:
   Check-PR-Reqs:
     runs-on: generic
     steps:
-      - name: Check if Jira ticket is added to PR body
-        id: check_body
+      - name: Check for any Jira IDs from PR description
+        id: matched_jira_ids
         env:
           PR_BODY: ${{ github.event.pull_request.body }}
+        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'skip-jira-validation') }}
         run: |
-          if [[ "$PR_BODY" =~ \|[\ ]?Jira\ ticket[\ ]?\|[\ ]?[LP|NEXFM][A-Z0-9]*[\ ]? ]]; then
-            echo "body_contains_jira=true" >> $GITHUB_ENV
-          else
-            echo "body_contains_jira=false" >> $GITHUB_ENV
+          # Match [A-Z0-9]-[0-9] as long as they have no [a-zA-Z] prefix or suffix
+          regex='(?<![a-zA-Z])[A-Z0-9]+?-[0-9]+(?![a-zA-Z])'
+          # For regex capture groups we need to use -P (perl regex flavor)
+          jira_ids=$(echo "${PR_BODY}" | grep -Po "${regex}" || true)
+          if [ -z "$jira_ids" ]; then
+            echo "++++++++++++++++++++++++++++++"
+            echo "ERROR:"
+            echo "Jira ID is not found in the PR description. Add the valid Jira ID in PR Description."
+            echo "To skip this check, add the label skip-jira-validation to the PR to skip this check."
+            echo "++++++++++++++++++++++++++++++"
             exit 1
           fi
+          jira_ids=$(echo $jira_ids | tr '\n' ' ')
+          echo "jira_ids=$jira_ids" >> $GITHUB_OUTPUT
+          echo "Jira IDs Found: $jira_ids"
+      - name: Validate Jira IDs using the Jira service
+        id: validate_jira_ids
+        env:
+          SYS_OIE_DEVOPS_JIRAAPI: ${{ secrets.SYS_OIE_DEVOPS_JIRAAPI }}
+        if: ${{ ! contains(github.event.pull_request.labels.*.name, 'skip-jira-validation') }}
+        run: |
+          failed_ids=""
+          for id in ${{ steps.matched_jira_ids.outputs.jira_ids }}; do
+            response=$(curl -vv -s -k \
+              -X GET verify=false \
+              -H "Authorization: Bearer ${SYS_OIE_DEVOPS_JIRAAPI}" \
+              -H "Content-Type: application/json" \
+              "https://jira.devtools.intel.com/rest/api/latest/issue/${id}")
+            echo "Checking for Jira ID ${id}"
+
+            if [[ "$response" == *"errorMessages"* ]]; then
+              failed_ids="${failed_ids} ${id}"
+            else
+              echo "Jira ID ${id} exists"
+            fi
+          done
+
+          if [[ -n "$failed_ids" ]]; then
+            echo "failed_ids=$failed_ids" >> $GITHUB_OUTPUT
+            echo "++++++++++++++++++++++++++++++"
+            echo "ERROR:"
+            echo "Jira ID(s)${failed_ids} specified in PR description does not exist. Use a valid Jira ID."
+            echo "To skip this check, add the label skip-jira-validation to the PR to skip this check."
+            echo "++++++++++++++++++++++++++++++"
+            exit 1
+          fi
+      - name: Post a comment on PR if Jira ID validation fails
+        id: post_comment
+        env:
+          SYS_OIE_DEVOPS_GITHUBAPI_TOKEN: ${{ secrets.SYS_OIE_DEVOPS_GITHUBAPI_TOKEN }}
+        if: ${{ success() || failure() }} && ${{ ! contains(github.event.pull_request.labels.*.name, 'skip-jira-validation') }}
+        run: |
+          if [[ -n "${{ steps.validate_jira_ids.outputs.failed_ids }}" ]]; then
+            curl -L -s -k \
+              -X POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Token ${SYS_OIE_DEVOPS_GITHUBAPI_TOKEN}" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              ${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments \
+              -d '{"body":"Jira ID(s)${{ steps.validate_jira_ids.outputs.failed_ids }} specified in PR description does not exist, use valid Jira IDs only. To skip this check, add the label ${{ github.server_url }}/${{ github.repository }}/labels/skip-jira-validation to the PR to skip this check."}'
+          fi
+          echo "Jira ID validation completed successfully"
